version: '3'
services:

  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: reservation
