version: '3'
services:

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: reservation

  app:
    build:
      context: "server"
    environment:
      - profile=$profile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - "postgres:database"

